### ISSUE TITLE
CC BY-SA?

### ISSUE THREAD

**Issue by xolotl** [piepdx/pie-cookbook#1]
Not sure if the PIE Cookbook plans to continue with the CC BY-SA license, but if it does, the SA restriction can cause friction for reuse of the Cookbook. IIUC, it means that Cookbook material could not be remixed with any material that has a clause like NC or ND as the resulting work could not carry the SA from the Cookbook license.

For example, if I wanted to create a handbook for a new accelerator by remixing parts of the PIE Cookbook licensed CC BY-SA and parts of another work that was licensed, say, CC BY-NC, I could not legally publish the resulting work because the CC BY-NC material cannot be changed to the CC BY-SA license that the Cookbook's SA clause would "demand".

I recommend the Cookbook adopt a simpler CC BY license to maximize reusability and yet maintain reference to the provenance of the Cookbook coming from PIE.

You can review a [CC license compatibility matrix](https://wiki.creativecommons.org/wiki/Wiki/cc_license_compatibility) online, and learn more about [SA compatibility](https://wiki.creativecommons.org/wiki/ShareAlike_compatibility) specifically.

**Comment by turoczy** [comment]
Thanks, @xolotl. I really appreciate the feedback and guidance. I understand what you're saying about the Share Alike friction. That was not our intent.

You correctly surmise what we would prefer to do:

> to maximize reusability and yet maintain reference to the provenance of the Cookbook coming from PIE

Any recommendations on a license that would make that feasible? Does the [previous CC0 1.0 Universal license](https://github.com/piepdx/pie-cookbook/commit/79cc200a7e54382f18b2c83f2e8bbabdbe122737) do a better job of what we're intending, in your opinion?

**Comment by xolotl** [comment]
I saw that the cookbook started with a CC0 license. CC0 of course would be the ultimate in promoting reusability and low friction. I think there are good reasons to use the plain CC BY however, as the attribution it requires generates a sort of paper trail that helps future consumers of cookbook goodness know from whence it came. That attribution, even if it is as general as to the project itself, can also honor those who have contributed to the cookbook. I would pick one of these: CC BY or CC0.

**Comment by rgleeson** [comment]
Thank you - we would like sourcing for original goodness...

**Comment by turoczy** [comment]
@xolotl I've updated the license to CC BY 4.0. Please let me know if that resolves the issue in your opinion.

**Comment by xolotl** [comment]
CC BY 4.0 is a great choice and matches what I understand the project's goals are.

**Comment by turoczy** [comment]
Thanks for the advice! Much appreciated.
