### ISSUE TITLE
Mentor integrity

### ISSUE THREAD

**Issue by Bwenamai** [piepdx/pie-cookbook#2]
Under Mentors.... discussion about mentors with their hands out, how to deal with mentors asking for fees, mentor integrity, that being a mentor is not necessarily an endorsement of character by  the accelerator

**Comment by turoczy** [comment]
Thanks for the suggestion @Bwenamai. We'll make sure to cover this!

**Comment by turoczy** [comment]
Added this to Notes. https://github.com/piepdx/pie-cookbook/blob/master/notes/mentors/mentor-integrity.md

**Comment by malieberman** [comment]
We have a mentor/protege agreement that covers the no solicitation issue. Happy to forward on.

**Comment by turoczy** [comment]
That would be awesome! Thank you

**Comment by malieberman** [comment]
Here you go. There are two docs in here. One for  the mentor and one for the protege (I hate the word mentee). 

Mark

**Comment by turoczy** [comment]
Not sure the attachments made it. Please feel free to send them to rick [at] piepdx [dot] com
