### ISSUE TITLE
impact of accelerators on founder families

### ISSUE THREAD

**Issue by camikaos** [piepdx/pie-cookbook#200]
https://github.com/piepdx/pie-cookbook/blob/master/drafts/working-draft-tactical.md#the-emotional-ebb-and-flow-of-a-stressful-startup-accelerator

" But we've found that paying attention to this emotional cycle — and managing the program accordingly — can be beneficial for founders, their partners, families, mentors, and the accelerator staff.”

**Comment by turoczy** [comment]
Great edit! I'll find some additional content to back this up.

**Comment by turoczy** [comment]
Thanks to your feedback, we'll also look at addressing this in #216

**Comment by turoczy** [comment]
Revised content in #228 and will continue chasing the issue throughout the document in #216. Closing this issue.
