### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by camikaos** [piepdx/pie-cookbook#201]
https://github.com/piepdx/pie-cookbook/blob/master/drafts/working-draft-tactical.md#pre-accelerator

"During that time, they've had a series of highs and lows where they've experienced any number leaps forward and, likely, an equal number of [setbacks.](url) I mean, that's why they're looking for some help, right?"

skipped word, add of

"During that time, they've had a series of highs and lows where they've experienced any number of leaps forward and, likely, an equal number of setbacks. I mean, that's why they're looking for some help, right?"

**Comment by turoczy** [comment]
Thank you! Fixed https://github.com/piepdx/pie-cookbook/pull/202
