### ISSUE TITLE
confusing image

### ISSUE THREAD

**Issue by camikaos** [piepdx/pie-cookbook#203]
![screen shot 2017-01-19 at 7 23 45 pm](https://cloud.githubusercontent.com/assets/14300761/22134576/eecdd20a-de7c-11e6-9e10-f6987ee9e4bd.png)

the 1 doesn't line up making the graph confusing

**Comment by turoczy** [comment]
Maybe we should just make the description currently labeled as 1 (https://github.com/piepdx/pie-cookbook/blob/master/drafts/working-draft-tactical.md#month-2-projections) part of the intro paragraph and remove "1" (and change 2 to 1…)?

**Comment by camikaos** [comment]
That's good.

**Comment by turoczy** [comment]
Corrected image in #217
