### ISSUE TITLE
confusing mentor comment

### ISSUE THREAD

**Issue by camikaos** [piepdx/pie-cookbook#204]
https://github.com/piepdx/pie-cookbook/blob/master/drafts/working-draft-tactical.md#tuesday

"Staff arrives. Continues making mentor connections for startups based on issues raised during family dinner. Typically two or three mentors per startup per issue."

Do you really typically assign two or three mentors per startup per issue? If so that's amazing (we have a hard time rounding up one mentor per event). I'm imagining a startup with ten issues and 30 mentors.

**Comment by turoczy** [comment]
@camikaos Better? #224

**Comment by turoczy** [comment]
Reviewed and accepted via #224
