### ISSUE TITLE
The value of collaboration over competition 

### ISSUE THREAD

**Issue by markdav-is** [piepdx/pie-cookbook#25]
One of the things I always appreciated about PIE was that it felt like it embodies the spirit of collaboration in Portland.  For example PIE seems at home in Centrl Office.  It's likely something that is obvious to folks who have spent a while in Portland or Austin, but it's slow to sink in to some cities.  There is a value in supporting other business incubators, maker spaces, coworking spaces, in your city and build a web of trust where everyone can feel safe and supported.  Competition in the classic capitalistic sense is toxic to the young businesses that need as much help and support as they can to get off the ground and should never need to feel like they are picking brands or picking sides and potentially burning bridges to get the help they need.  It might seem obvious to the cookbook authors, but it's worth explaining as it's a new concept to many folks.

**Comment by turoczy** [comment]
Thanks so much for this perspective!

**Comment by turoczy** [comment]
Added this to the outline (https://github.com/piepdx/pie-cookbook/pull/26) so I'm closing out this issue.
