### ISSUE TITLE
Missing Index

### ISSUE THREAD

**Issue by elliottpayne** [piepdx/pie-cookbook#349]
The whole book could use an index at the beginning for easier navigation

**Comment by turoczy** [comment]
Thank @elliottpayne! We tore out the table of contents in the working doc. But the last published draft has a working ToC. (https://github.com/piepdx/pie-cookbook/blob/master/docs/pie-cookbook-0.9.md) Does that address this issue or were you looking for something more descriptive?

**Comment by turoczy** [comment]
Also, this isn't ready for prime time, yet, but… we will be working on a far more accessible and legible format powered by Read The Docs http://pie-cookbook.readthedocs.io/en/latest/

**Comment by elliottpayne** [comment]
This is great. Thanks!
