### ISSUE TITLE
Add a TOC

### ISSUE THREAD

**Issue by nickmccarty** [piepdx/pie-cookbook#354]
Adding a table of contents would greatly improve readability, as a user has to scroll for some time before encountering the Introduction section of the Cookbook (after being taken for quite a ride with the lengthy Preface).

Happy to help, if needed 😃

**Comment by turoczy** [comment]
@nickmccarty Thank you! There's a Table of Contents in the current version https://github.com/piepdx/pie-cookbook/blob/master/docs/pie-cookbook-0.9.md. Please advise as to where you encountered the version without a TOC and I'll make sure to get that corrected. 

P.S. For even better readability, there's a Read the Docs version, as well https://pie-cookbook.readthedocs.io/en/latest/

**Comment by nickmccarty** [comment]
Awesome, thanks for pointing me to that @turoczy!

What I read was the working draft:

https://github.com/piepdx/pie-cookbook/blob/master/drafts/current/pie-cookbook-working-draft.md

**Comment by turoczy** [comment]
Got it! Thanks again @nickmccarty!
