### ISSUE TITLE
Ghost Peppers

### ISSUE THREAD

**Issue by enam** [piepdx/pie-cookbook#4]
I like that the outline looks focused on positives; what to do rather than not do. But having the occasional "⚠️🌶 Danger, Do Not Put This Ingredient Is Your Pie" notes, anecdotal or otherwise, could be useful in sections where you do have cautionary tales.

**Comment by enam** [comment]
PS, I'd like to add the "suggestion" label, but it does not appear I can add a label to the issue. May be limited to team members.

**Comment by turoczy** [comment]
Labeled! And great feedback. 

We've got a current placeholder for that sort of stuff under "mistakes were made." At this point, I'm assuming these will live contextually throughout the cookbook. But this is also a great reminder that we can be making qualitative judgements on what not to do, based on our experience, even if we never made that mistake ourselves.
