### ISSUE TITLE
Breaking down silos

### ISSUE THREAD

**Issue by turoczy** [piepdx/pie-cookbook#47]
Share PIE experience on breaking down silos:
- Within communities
- Within corporations
- Between startups and corporations
- Between startups and design
- Between different startup verticals

(via @nohorse)

**Comment by jrgifford** [comment]
Do you have experience with breaking down silos between different VC/incubators? That's something I've always wonder - does it have to be this "us vs them" mentality, and are there others that have gotten around it?

**Comment by turoczy** [comment]
@jrgifford We've got a pretty collaborative community here in Portland. Maybe I was working under the assumption that was not unique. I'll try to put some thought to capturing that "rising water floats all boats" dynamic, as opposed to the "us vs them" mentality. Thank you! ❤️

**Comment by turoczy** [comment]
Added this to the main document, so I'm going to close it out here. (We still need to build the content, but the placeholder is there.)
