### ISSUE TITLE
Suggested topics?

### ISSUE THREAD

**Issue by turoczy** [piepdx/pie-cookbook#5]
As part of [our Kickstarter campaign](https://www.kickstarter.com/projects/turoczy/pie-cookbook-an-open-source-guide-for-startup-acce), we're asking our backers to vote on the topics that are most important to them. That way, we can focus our time and energy on the highest priority areas for our community, first. 

That said, **we'd still love to have a breadth of topics to cover.** So we want to hear from you. What topics would you like to see us covering in the PIE Cookbook? 

If you need some inspiration, [we've started roughing out an outline of potential topics](https://github.com/piepdx/pie-cookbook/blob/master/notes/outline.md).

**Comment by turoczy** [comment]
Here's an example of suggested content https://github.com/piepdx/pie-cookbook/issues/4

**Comment by Bwenamai** [comment]
explicit give before you get for accelerators.
doing the work
what an investor looks like? monetary, connector, champion, others?
as a founder you really aren't all that so, DO THE WORK! (theme?)
decision making.... to steal yogi berra "If you come to a fork in the road, take it"

**Comment by Bwenamai** [comment]
doer culture.... why having people doing businesses vs working on projects is important.

**Comment by turoczy** [comment]
We start to touch on this a bit in the selection process https://github.com/piepdx/pie-cookbook/blob/master/notes/startups/startups-selecting.md 

> The driving idea must not be about seeing a product come to fruition. The driving idea must be about building a scalable and sustainable business.

But I'll make sure that we blow this out more explicitly.

**Comment by turoczy** [comment]
Housekeeping: We've captured these comments in the outline and the working drafts so I'm going to close this out. We need to focus on the topics at hand before exploring more topics.
