### ISSUE TITLE
Metrics for Success

### ISSUE THREAD

**Issue by markdav-is** [piepdx/pie-cookbook#6]
I've been hearing lots of "X jobs created" metrics in interviews with local accelerators.  It makes me cringe because that's not what I feel accelerators really accomplish.  At best, they are double-dipping those numbers from the businesses that go thru the accelerator who are actually doing the hiring.  If you could explain some metrics for success and how to collect and gauge those metrics I feel that would be helpful.

**Comment by turoczy** [comment]
Yes, there are the common metrics upon which accelerators are judged: amount of funding raised, number of jobs created, valuation, exits… PIE has always focused on "building better founders," and we've still managed to hit decent expected metrics. What metrics do folks think accelerators should be tracking/valuing instead?

**Comment by markdav-is** [comment]
Whatever the metric are, they should be a function of the effort of the accelerator and not so much the companies that run thru it.  It's tricky I'm sure.  How companies are helped by accelerators feels hard to measure.  Sorry I don't have more direct input.  The value of accelerators feels more soft than hard to me, so putting hard numbers around it is challenging.

**Comment by turoczy** [comment]
I think we can be discrete about the metrics for the accelerator itself, the companies it supports, and maybe even the community that supports it. Agree that there are far more quantitative and qualitative metrics that can help provide insights into accelerator impact. 

This discussion has a placeholder in https://github.com/piepdx/pie-cookbook/blob/master/notes/outline.md so I'm closing it out.
