### ISSUE TITLE
Where does outline end and content begin?

### ISSUE THREAD

**Issue by turoczy** [piepdx/pie-cookbook#8]
As I'm working to build out the outline for the Cookbook (https://github.com/piepdx/pie-cookbook/blob/master/notes/outline.md), I find myself falling into bigger copy blocks from time to time. Is this okay? Is this a signal to start a more formalized copy block on the subject and move it from "outline" to actual "content"? Thoughts?

**Comment by Bwenamai** [comment]
I think brain dumping when the thought hits is key. content can always be moved from the outline.  The content may also trigger more subsections in the outline?
